from __future__ import annotations

import os

import google.generativeai as genai


def generate_explanation(prediction: str, confidence: float, probabilities: dict):
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        return build_fallback_explanation(prediction, confidence, probabilities)

    try:
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel("gemini-1.5-flash")
        prompt = (
            "You are an expert Clinical Decision Support AI specialist for BrainCare AI System. "
            "Provide a precise, highly professional clinical MRI analysis summary. "
            f"The deep learning engine classified the brain MRI scan as: {prediction} with a confidence score of {confidence * 100:.1f}%. "
            f"Class probability distribution: {probabilities}. "
            "Structure the response clearly into: "
            "1) Clinical Finding Summary, "
            "2) Spatial & Feature Pathological Overview, "
            "3) Radiologist Decision Support Note. "
            "Use authoritative, medical-grade clinical terminology."
        )
        response = model.generate_content(prompt)
        return response.text
    except Exception:
        return build_fallback_explanation(prediction, confidence, probabilities)


def build_fallback_explanation(prediction: str, confidence: float, probabilities: dict):
    conf_pct = f"{confidence * 100:.1f}%" if confidence <= 1.0 else f"{confidence:.1f}%"
    
    if prediction.lower() == "notumor":
        analysis = (
            "Clinical MRI Analysis indicates negative findings for tumor mass pathology across evaluated spatial features. "
            "Ventricular structures and cerebral parenchymal signals remain within standard anatomical baselines."
        )
    else:
        analysis = (
            f"Clinical AI Deep Diagnostics identified characteristic MRI feature signals indicative of {prediction.capitalize()}. "
            f"Spatial feature map correlation confirms localized intensity concentration with a model confidence rating of {conf_pct}."
        )

    prob_summary = ", ".join([f"{k.capitalize()}: {v*100:.1f}%" for k, v in probabilities.items()])

    return (
        f"{analysis} "
        f"Evaluated Probability Distribution: [{prob_summary}]. "
        "Generated by BrainCare AI Clinical Diagnostics Engine for radiologist decision support and report validation."
    )

